(() => {
  "use strict";

  const LEGAL_I18N = {
    id: {
      "lg.back": "Beranda",
      "lg.badge": "Legal",
      "ft.privacy": "Kebijakan Privasi",
      "ft.terms": "Syarat & Ketentuan",
      "pp.title": "Kebijakan Privasi",
      "pp.updated": "Terakhir diperbarui: 24 Agustus 2026",
      "pp.s1t": "1. Informasi yang Kami Kumpulkan",
      "pp.s1p": "Saat kamu menggunakan layanan Noisy Verse, kami hanya mengumpulkan data yang diperlukan untuk memproses pesanan:",
      "pp.s1i1": "<strong>Nama pengguna Telegram</strong> — sebagai media komunikasi dan pengiriman hasil.",
      "pp.s1i2": "<strong>URL yang kamu kirim</strong> — website atau repository GitHub yang ingin di-reverse.",
      "pp.s1i3": "<strong>Bukti pembayaran</strong> — dikirim langsung melalui chat dan hanya disimpan selama dibutuhkan.",
      "pp.s2t": "2. Penggunaan Informasi",
      "pp.s2p": "Seluruh data yang kami terima digunakan semata-mata untuk:",
      "pp.s2i1": "Memproses permintaan reverse prompt kamu.",
      "pp.s2i2": "Mengirimkan hasil scraping dan design system.",
      "pp.s2i3": "Memberikan bantuan teknis dan klaim garansi.",
      "pp.s2p2": "Kami <strong>tidak menjual, menyewakan, atau membagikan</strong> data pribadi kamu kepada pihak ketiga dalam bentuk apa pun.",
      "pp.s3t": "3. URL yang Kamu Kirim",
      "pp.s3p": "URL yang kamu kirim hanya diproses untuk menghasilkan prompt dan <strong>tidak dibagikan secara publik</strong>. Kami tidak menyimpan arsip hasil scraping milik kamu tanpa persetujuan.",
      "pp.s4t": "4. Penyimpanan & Keamanan Data",
      "pp.s4p": "Data transaksi hanya disimpan pada percakapan Telegram kami dan tidak dipindahkan ke server lain. Bukti pembayaran dapat dihapus atas permintaan setelah pesanan selesai dan masa garansi berakhir.",
      "pp.s5t": "5. Cookie & Pelacakan",
      "pp.s5p": "Website ini tidak menggunakan cookie pelacakan, iklan pihak ketiga, maupun alat analitik yang mengumpulkan data pengunjung. Hanya font dan ikon dari CDN publik yang dimuat agar tampilan website berfungsi.",
      "pp.s6t": "6. Hak Kamu",
      "pp.s6i1": "Meminta penghapusan data atau bukti transaksi yang tersimpan di percakapan.",
      "pp.s6i2": "Menanyakan data apa saja yang kami simpan tentang kamu.",
      "pp.s6i3": "Menarik persetujuan komunikasi kapan saja.",
      "pp.s7t": "7. Hubungi Kami",
      "pp.s7p": "Ada pertanyaan soal privasi data kamu? Hubungi kami langsung:",
      "ts.title": "Syarat & Ketentuan",
      "ts.updated": "Terakhir diperbarui: 24 Agustus 2026",
      "ts.s1t": "1. Ketentuan Umum",
      "ts.s1p": "Dengan menggunakan layanan Noisy Verse, kamu dianggap telah membaca, memahami, dan menyetujui seluruh syarat dan ketentuan yang berlaku di halaman ini.",
      "ts.s2t": "2. Produk & Layanan",
      "ts.s2i1": "Kami menyediakan layanan reverse prompt: mengubah website atau repository GitHub menjadi prompt AI terstruktur.",
      "ts.s2i2": "Waktu proses umumnya beberapa detik hingga menit per URL tergantung antrean dan ukuran target.",
      "ts.s2i3": "Hasil dikirim melalui Telegram sesuai paket yang dibeli.",
      "ts.s3t": "3. Tanggung Jawab Pengguna",
      "ts.s3i1": "Kamu wajib memiliki hak atau izin atas URL/repo yang dikirim untuk di-reverse.",
      "ts.s3i2": "Dilarang menggunakan layanan untuk me-reverse konten yang melanggar hukum atau hak cipta pihak lain.",
      "ts.s3i3": "Penyalahgunaan layanan dapat menyebabkan pesanan ditolak tanpa refund.",
      "ts.s4t": "4. Pembayaran",
      "ts.s4i1": "Pembayaran dilakukan sebelum proses scraping dimulai.",
      "ts.s4i2": "Harga dapat berubah sewaktu-waktu; harga yang berlaku adalah saat pesanan dikonfirmasi.",
      "ts.s4i3": "Simpan bukti pembayaran sebagai dasar klaim.",
      "ts.s5t": "5. Garansi",
      "ts.s5p": "Garansi berlaku apabila permintaan gagal diproses sepenuhnya karena kesalahan sistem kami. URL yang tidak dapat diakses, dilindungi login, atau memblokir akses scraper <strong>tidak termasuk garansi</strong>, namun dapat diganti dengan URL lain selama kuota masih tersedia.",
      "ts.s6t": "6. Refund",
      "ts.s6p": "Pengembalian dana hanya berlaku jika kami gagal memproses pesanan kamu sepenuhnya dan tidak ada solusi pengganti yang disetujui kedua belah pihak. Kuota yang sudah terpakai tidak dapat direfund.",
      "ts.s7t": "7. Perubahan Ketentuan",
      "ts.s7p": "Kami berhak memperbarui syarat dan ketentuan ini sewaktu-waktu. Perubahan akan berlaku sejak dipublikasikan di halaman ini.",
      "ts.s8t": "8. Hubungi Kami",
      "ts.s8p": "Pertanyaan seputar pesanan atau kerja sama:"
    },
    en: {
      "lg.back": "Home",
      "lg.badge": "Legal",
      "ft.privacy": "Privacy Policy",
      "ft.terms": "Terms of Service",
      "pp.title": "Privacy Policy",
      "pp.updated": "Last updated: August 24, 2026",
      "pp.s1t": "1. Information We Collect",
      "pp.s1p": "When you use the Noisy Verse service, we only collect the data required to process your order:",
      "pp.s1i1": "<strong>Telegram username</strong> — as our communication and result delivery channel.",
      "pp.s1i2": "<strong>URLs you submit</strong> — the websites or GitHub repositories you want to reverse.",
      "pp.s1i3": "<strong>Payment proof</strong> — sent directly via chat and stored only as long as needed.",
      "pp.s2t": "2. Use of Information",
      "pp.s2p": "All data we receive is used solely to:",
      "pp.s2i1": "Process your reverse prompt requests.",
      "pp.s2i2": "Deliver scraping results and design systems.",
      "pp.s2i3": "Provide technical support and warranty claims.",
      "pp.s2p2": "We <strong>never sell, rent, or share</strong> your personal data with any third party in any form.",
      "pp.s3t": "3. URLs You Submit",
      "pp.s3p": "Submitted URLs are processed solely to generate prompts and are <strong>never shared publicly</strong>. We do not archive your scrape results without your consent.",
      "pp.s4t": "4. Data Storage & Security",
      "pp.s4p": "Transaction data stays within our Telegram conversations and is never moved to other servers. Payment proof can be deleted on request once your order and warranty period end.",
      "pp.s5t": "5. Cookies & Tracking",
      "pp.s5p": "This website uses no tracking cookies, third-party ads, or analytics that collect visitor data. Only fonts and icons from public CDNs are loaded so the site renders correctly.",
      "pp.s6t": "6. Your Rights",
      "pp.s6i1": "Request deletion of data or transaction proof stored in our chats.",
      "pp.s6i2": "Ask what data we store about you.",
      "pp.s6i3": "Withdraw communication consent at any time.",
      "pp.s7t": "7. Contact Us",
      "pp.s7p": "Questions about your data privacy? Reach us directly:",
      "ts.title": "Terms & Conditions",
      "ts.updated": "Last updated: August 24, 2026",
      "ts.s1t": "1. General Terms",
      "ts.s1p": "By using the Noisy Verse service, you are deemed to have read, understood, and agreed to all terms and conditions on this page.",
      "ts.s2t": "2. Products & Services",
      "ts.s2i1": "We provide a reverse prompt service: turning websites or GitHub repositories into structured AI prompts.",
      "ts.s2i2": "Processing usually takes seconds to minutes per URL depending on queue and target size.",
      "ts.s2i3": "Results are delivered via Telegram according to your purchased plan.",
      "ts.s3t": "3. User Responsibilities",
      "ts.s3i1": "You must have the rights or permission to reverse the URLs/repos you submit.",
      "ts.s3i2": "Using the service to reverse content that breaks the law or others' copyright is prohibited.",
      "ts.s3i3": "Abuse of the service may lead to order rejection without refund.",
      "ts.s4t": "4. Payment",
      "ts.s4i1": "Payment is made before scraping starts.",
      "ts.s4i2": "Prices may change at any time; the applicable price is the one confirmed at order time.",
      "ts.s4i3": "Keep your payment proof for warranty claims.",
      "ts.s5t": "5. Warranty",
      "ts.s5p": "Warranty applies when a request fully fails due to faults in our system. URLs that are inaccessible, login-protected, or block scrapers are <strong>not covered</strong>, but may be swapped for another URL while quota remains.",
      "ts.s6t": "6. Refund",
      "ts.s6p": "Refunds apply only if we fully fail to process your order and no alternative solution is agreed by both parties. Used quota is non-refundable.",
      "ts.s7t": "7. Changes to Terms",
      "ts.s7p": "We may update these terms at any time. Changes take effect once published on this page.",
      "ts.s8t": "8. Contact Us",
      "ts.s8p": "Questions about orders or partnerships:"
    }
  };

  const I18N = {
    id: {
      "nav.try": "Reverse",
      "nav.reverse": "Reverse",
      "nav.login": "Masuk",
      "nav.features": "Keunggulan",
      "nav.how": "Cara Kerja",
      "nav.pricing": "Harga",
      "nav.testi": "Testimoni",
      "nav.faq": "FAQ",
      "hero.badge": "Website &amp; Repo · Jadi Prompt AI",
      "hero.title1": "Website Apapun,",
      "hero.title2": "Jadi Prompt AI.",
      "hero.sub": "Tempel URL website atau repo GitHub, dapatkan prompt AI lengkap plus design system-nya. Siap dipakai untuk bikin ulang project.",
      "hero.cta": "Coba Gratis",
      "hero.cta2": "Chat Telegram",
      "mq.1": "Website to Prompt",
      "mq.2": "Repo to Prompt",
      "mq.3": "Design System",
      "mq.4": "Hasil Instan",
      "mq.5": "Support SSE Stream",
      "feat.title": 'Kenapa harus <span class="accent">Noisy Verse?</span>',
      "feat.sub": "Satu URL, prompt AI lengkap langsung di tangan.",
      "feat.1.t": "Website Apapun Jadi Prompt",
      "feat.1.p": "Tempel URL website apa saja, struktur dan design-nya diubah jadi prompt AI terstruktur yang siap dipakai untuk rebuild project.",
      "feat.2.t": "Repo GitHub Juga Bisa",
      "feat.2.p": "Cukup format owner/repo atau link GitHub penuh, prompt-nya langsung jadi.",
      "feat.3.t": "Gratis Design System",
      "feat.3.p": "Hasil scraping menyertakan design system yang bisa dibuka langsung.",
      "feat.4.t": "Hasil Instan",
      "feat.4.p": "Proses hanya beberapa detik per URL, streaming realtime.",
      "feat.5.t": "Mode Bulk",
      "feat.5.p": "Butuh banyak prompt sekaligus? Kirim satu permintaan, hasil banyak.",
      "how.title": 'Cara kerjanya <span class="accent">3 langkah.</span>',
      "how.1.t": "Tempel URL",
      "how.1.p": 'Kirim link website atau repo GitHub kamu via Telegram <a href="https://t.me/noisy02" target="_blank" rel="noopener">@noisy02</a>.',
      "how.2.t": "Proses Scraping",
      "how.2.p": "Sistem menganalisis struktur, konten, dan design-nya secara otomatis.",
      "how.3.t": "Prompt Terkirim",
      "how.3.p": "Prompt AI lengkap plus design system langsung dikirim ke kamu.",
      "price.title": "Pilih paketmu.",
      "price.sub": "Sekali bayar, scraping sepuasnya.",
      "price.1.t": "Coba Dulu",
      "price.1.u": "/ 5 URL",
      "price.2.t": "Hemat",
      "price.2.u": "/ 50 URL",
      "price.3.t": "Unlimited",
      "price.3.u": "/ 1 bulan",
      "price.flag": "Terlaris",
      "price.buy": "Beli Sekarang",
      "price.1.f": "Website to prompt",
      "price.1.f2": "Repo to prompt",
      "price.1.f3": "Hasil via Telegram",
      "price.2.f": "Semua fitur scraping",
      "price.2.f2": "10x generate PRD AI",
      "price.2.f3": "Design system disertakan",
      "price.2.f4": "Mode bulk",
      "price.2.f5": "Prioritas antrian",
      "price.3.f": "Scraping tanpa batas",
      "price.3.f2": "30x generate PRD AI",
      "price.3.f3": "Semua fitur premium",
      "price.3.f4": "Support prioritas 24/7",
      "price.3.f5": "Update fitur gratis selamanya",
      "testi.title": "Kata mereka.",
      "stats.title": 'Angka Yang <span class="accent">Berbicara.</span>',
      "stats.sub": "Hasil nyata yang mencerminkan pertumbuhan dan kepercayaan kreator.",
      "stats.cta": "Mulai Sekarang",
      "stats.visits": "Total Kunjungan",
      "stats.unique": "Pengunjung Unik",
      "stats.reverses": "Reverse Dikerjakan",
      "stats.prd": "PRD Dibuat",
      "stats.live": "kreator sedang online sekarang",
      "testi.1": '"Tinggal tempel URL, prompt-nya langsung jadi. Bikin ulang website klien jadi jauh lebih cepat."',
      "testi.1.by": "Rizky — Web Developer",
      "testi.2": '"Fitur repo to prompt-nya akurat banget, struktur project kebaca rapi. Recommended."',
      "testi.2.by": "Dinda — Freelance Dev",
      "testi.3": '"Design system yang disertakan bikin hasil rebuild-nya mirip banget sama aslinya. Worth it."',
      "testi.3.by": "Fajar — UI Designer",
      "cta.title": 'Siap reverse <span class="accent-glow">project pertamamu?</span>',
      "cta.sub": "Kirim URL kamu sekarang, prompt jadi dalam hitungan detik.",
      "cta.buy": "Coba Gratis",
      "cta.tg": "Telegram",
      "faq.title": 'Pertanyaan <span class="accent">umum.</span>',
      "faq.sub": "Hal-hal yang paling sering ditanyakan sebelum mulai.",
      "faq.q1": "Apa itu Noisy Verse?",
      "faq.a1": "Noisy Verse mengubah URL website atau repo GitHub apa pun menjadi prompt AI lengkap beserta design system-nya, siap dipakai untuk membangun ulang project.",
      "faq.q2": "Apa beda Reverse website dan repo?",
      "faq.a2": "Reverse website membaca tampilan & struktur halaman jadi prompt plus design system. Reverse repo membaca struktur kode project GitHub menjadi prompt yang rapi.",
      "faq.q3": "Berapa lama proses reverse-nya?",
      "faq.a3": "Umumnya hanya beberapa detik. Untuk website atau repo besar bisa sedikit lebih lama, tapi tetap real-time lewat streaming.",
      "faq.q4": "Bagaimana cara bayar dan mengaktifkan paket?",
      "faq.a4": "Pilih paket di halaman Harga, buat kode pesanan, bayar via QRIS/transfer, lalu konfirmasi ke bot Telegram. Paket aktif otomatis setelah kami ACC.",
      "faq.q5": "Apa itu kuota GitVerse?",
      "faq.a5": "Kuota GitVerse adalah jumlah reverse yang bisa kamu jalankan. Paket Premium punya kuota tetap yang terlihat di halaman Reverse, sedangkan paket Unlimited bebas tanpa batas.",
      "faq.q6": "Bagaimana memakai kupon diskon?",
      "faq.a6": "Masukkan kode kupon di halaman pembayaran lalu klik Terapkan. Jika valid, harga paket langsung terpotong sebelum kamu buat pesanan.",
      "footer.privacy": "Kebijakan Privasi",
      "footer.terms": "Syarat & Ketentuan"
    },
    en: {
      "nav.try": "Reverse",
      "nav.reverse": "Reverse",
      "nav.login": "Sign in",
      "nav.features": "Features",
      "nav.how": "How it works",
      "nav.pricing": "Pricing",
      "nav.testi": "Testimonials",
      "nav.faq": "FAQ",
      "hero.badge": "Websites &amp; Repos · Into AI Prompts",
      "hero.title1": "Any Website,",
      "hero.title2": "Into an AI Prompt.",
      "hero.sub": "Paste a website URL or GitHub repo and get a complete AI prompt plus its design system. Ready to rebuild your project.",
      "hero.cta": "Try Free",
      "hero.cta2": "Chat on Telegram",
      "mq.1": "Website to Prompt",
      "mq.2": "Repo to Prompt",
      "mq.3": "Design System",
      "mq.4": "Instant Results",
      "mq.5": "SSE Stream Support",
      "feat.title": 'Why choose <span class="accent">Noisy Verse?</span>',
      "feat.sub": "One URL, a complete AI prompt in your hands.",
      "feat.1.t": "Any Website Becomes a Prompt",
      "feat.1.p": "Paste any website URL and its structure and design become a structured AI prompt, ready to rebuild the project.",
      "feat.2.t": "GitHub Repos Too",
      "feat.2.p": "Just use owner/repo format or a full GitHub link and the prompt is generated instantly.",
      "feat.3.t": "Free Design System",
      "feat.3.p": "Every scrape includes a design system you can open right away.",
      "feat.4.t": "Instant Results",
      "feat.4.p": "Takes only seconds per URL with realtime streaming.",
      "feat.5.t": "Bulk Mode",
      "feat.5.p": "Need many prompts at once? Send one request, get many results.",
      "how.title": 'How it works — <span class="accent">3 steps.</span>',
      "how.1.t": "Paste URL",
      "how.1.p": 'Send your website or GitHub repo link via Telegram <a href="https://t.me/noisy02" target="_blank" rel="noopener">@noisy02</a>.',
      "how.2.t": "We Scrape It",
      "how.2.p": "The system automatically analyzes its structure, content, and design.",
      "how.3.t": "Prompt Delivered",
      "how.3.p": "The complete AI prompt plus design system is sent straight to you.",
      "price.title": "Pick your plan.",
      "price.sub": "Pay once, scrape as much as you like.",
      "price.1.t": "Starter",
      "price.1.u": "/ 5 URLs",
      "price.2.t": "Saver",
      "price.2.u": "/ 50 URLs",
      "price.3.t": "Unlimited",
      "price.3.u": "/ 1 month",
      "price.flag": "Most Popular",
      "price.buy": "Buy Now",
      "price.1.f": "Website to prompt",
      "price.1.f2": "Repo to prompt",
      "price.1.f3": "Results via Telegram",
      "price.2.f": "All scraping features",
      "price.2.f2": "10x AI PRD generations",
      "price.2.f3": "Design system included",
      "price.2.f4": "Bulk mode",
      "price.2.f5": "Priority queue",
      "price.3.f": "Unlimited scraping",
      "price.3.f2": "30x AI PRD generations",
      "price.3.f3": "All premium features",
      "price.3.f4": "24/7 priority support",
      "price.3.f5": "Free feature updates forever",
      "testi.title": "What they say.",
      "stats.title": 'Numbers That <span class="accent">Speak.</span>',
      "stats.sub": "Real numbers reflecting our growth and the trust of creators.",
      "stats.cta": "Get Started",
      "stats.visits": "Total Visits",
      "stats.unique": "Unique Visitors",
      "stats.reverses": "Reverses Completed",
      "stats.prd": "PRDs Created",
      "stats.live": "creators online right now",
      "testi.1": '"Just paste a URL and the prompt is ready. Rebuilding client sites is way faster now."',
      "testi.1.by": "Rizky — Web Developer",
      "testi.2": '"The repo to prompt feature is spot on — project structure reads cleanly. Recommended."',
      "testi.2.by": "Dinda — Freelance Dev",
      "testi.3": '"The included design system makes rebuilds look almost identical to the original. Worth it."',
      "testi.3.by": "Fajar — UI Designer",
      "cta.title": 'Ready to reverse <span class="accent-glow">your first project?</span>',
      "cta.sub": "Send your URL now — the prompt is ready in seconds.",
      "cta.buy": "Try Free",
      "cta.tg": "Telegram",
      "faq.title": 'Frequently <span class="accent">asked.</span>',
      "faq.sub": "The things people ask most before getting started.",
      "faq.q1": "What is Noisy Verse?",
      "faq.a1": "Noisy Verse turns any website URL or GitHub repo into a complete AI prompt along with its design system, ready to rebuild the project.",
      "faq.q2": "What's the difference between website and repo reverse?",
      "faq.a2": "Website reverse reads a page's look & structure into a prompt plus a design system. Repo reverse reads a GitHub project's code structure into a clean prompt.",
      "faq.q3": "How long does a reverse take?",
      "faq.a3": "Usually just a few seconds. Larger sites or repos may take a bit longer, but it streams in real time.",
      "faq.q4": "How do I pay and activate a package?",
      "faq.a4": "Pick a package on the Pricing page, generate an order code, pay via QRIS/transfer, then confirm on the Telegram bot. Your package activates automatically once we approve it.",
      "faq.q5": "What is the GitVerse quota?",
      "faq.a5": "The GitVerse quota is how many reverses you can run. The Premium package has a fixed quota shown on the Reverse page, while the Unlimited package has no limit.",
      "faq.q6": "How do I use a discount coupon?",
      "faq.a6": "Enter the coupon code on the payment page and click Apply. If it's valid, the package price is discounted before you create your order.",
      "footer.privacy": "Privacy Policy",
      "footer.terms": "Terms of Service"
    }
  };

  const PAY_I18N = {
    id: {
      "pay.title": "Selesaikan pembayaran.",
      "pay.sub": "Pilih paket, bayar, lalu konfirmasi lewat bot Telegram.",
      "pay.package": "Paket kamu",
      "pay.tg": "Username Telegram kamu",
      "pay.tg.ph": "@username",
      "pay.create": "Buat Kode Pesanan",
      "pay.method": "Metode pembayaran",
      "pay.qris": "QRIS — scan semua e-wallet & m-banking",
      "pay.bank": "Transfer Bank",
      "pay.confirm": "Konfirmasi via Bot Telegram",
      "pay.confirm.chat": "Konfirmasi via Chat Telegram",
      "pay.step1": "Isi username Telegram & buat kode pesanan.",
      "pay.step2": "Bayar sesuai nominal paket lewat QRIS / transfer.",
      "pay.step3": "Kirim bukti bayar ke bot Telegram, kami proses segera.",
      "pay.created": "Kode pesanan kamu:",
      "pay.note": "Setelah bayar, kirim bukti transfer ke bot — pesananmu langsung masuk antrian.",
      "pay.back": "Kembali ke beranda",
      "pay.err.tg": "Isi username Telegram dulu ya."
    },
    en: {
      "pay.title": "Complete your payment.",
      "pay.sub": "Pick a plan, pay, then confirm via our Telegram bot.",
      "pay.package": "Your plan",
      "pay.tg": "Your Telegram username",
      "pay.tg.ph": "@username",
      "pay.create": "Create Order Code",
      "pay.method": "Payment method",
      "pay.qris": "QRIS — works with all e-wallets & m-banking",
      "pay.bank": "Bank Transfer",
      "pay.confirm": "Confirm via Telegram Bot",
      "pay.confirm.chat": "Confirm via Telegram Chat",
      "pay.step1": "Fill in your Telegram username & create an order code.",
      "pay.step2": "Pay the plan amount via QRIS / bank transfer.",
      "pay.step3": "Send your payment proof to the bot — we process it right away.",
      "pay.created": "Your order code:",
      "pay.note": "After paying, send your proof to the bot — your order enters the queue instantly.",
      "pay.back": "Back to home",
      "pay.err.tg": "Please fill in your Telegram username first."
    }
  };

  function dict() {
    const lang = localStorage.getItem("nv_lang") || "id";
    return lang === "en" ? { lang, d: { ...I18N.en, ...PAY_I18N.en, ...LEGAL_I18N.en } } : { lang, d: { ...I18N.id, ...PAY_I18N.id, ...LEGAL_I18N.id } };
  }

  function apply() {
    const { lang, d } = dict();
    document.documentElement.lang = lang;
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const v = d[el.dataset.i18n];
      if (v != null) el.innerHTML = v;
    });
    document.querySelectorAll("[data-i18n-ph]").forEach((el) => {
      const v = d[el.dataset.i18nPh];
      if (v != null) el.placeholder = v;
    });
    document.querySelectorAll(".lang-btn").forEach((b) => {
      b.classList.toggle("active", b.dataset.lang === lang);
    });
  }

  function init() {
    document.querySelectorAll(".lang-btn").forEach((btn) => {
      btn.addEventListener("click", () => {
        if (btn.dataset.lang === (localStorage.getItem("nv_lang") || "id")) return;
        localStorage.setItem("nv_lang", btn.dataset.lang);
        apply();
        document.dispatchEvent(new CustomEvent("nv:langchange", { detail: { lang: btn.dataset.lang } }));
      });
    });
    apply();
  }

  init();

  window.NoisyLang = { apply, dict };
})();
